import {
  createContext,
  useContext,
  useState,
  useEffect,
  useCallback,
} from "react";

/* ─── Translations ──────────────────────────── */
const translations = {
  en: {
    nav: {
      dashboard: "Dashboard",
      products: "Products",
      orders: "Orders",
      store: "Store Settings",
      publicStore: "My Store",
      logout: "Logout",
    },
    landing: {
      hero_eyebrow: "Introducing Vendors",
      hero_title: "Your store,\neverywhere.",
      hero_subtitle:
        "Launch your e-commerce store in minutes. Manage products, track orders, and customize your brand — all in one place.",
      cta_start: "Start for free",
      cta_login: "Sign in",
      tab_setup: "Store Setup",
      tab_products: "Products",
      tab_orders: "Orders",
      tab_customize: "Customize",
      feature_title: "Everything you need\nto sell online.",
      f1_title: "Instant storefront",
      f1_desc:
        "Get a beautiful, branded store in seconds. Share your link and start selling.",
      f2_title: "Product management",
      f2_desc:
        "Add, edit, and organize products. Upload photos and set inventory levels.",
      f3_title: "Order tracking",
      f3_desc:
        "See every order in real time. Update statuses and keep customers informed.",
      f4_title: "Custom branding",
      f4_desc: "Choose your colors, upload a banner, and make the store yours.",
      trusted: "Trusted by growing businesses",
      cta_section: "Ready to start selling?",
      cta_sub: "Create your free store today. No credit card required.",
      cta_btn: "Create your store",
    },
    auth: {
      login_title: "Welcome back",
      login_sub: "Sign in to your Vendors account",
      register_title: "Create your store",
      register_sub: "Start selling in minutes — free",
      name: "Full name",
      email: "Email address",
      password: "Password",
      login_btn: "Sign in",
      register_btn: "Create account",
      no_account: "Don't have an account?",
      have_account: "Already have an account?",
      register_link: "Create one",
      login_link: "Sign in",
      logging_in: "Signing in…",
      registering: "Creating account…",
    },
    dashboard: {
      title: "Dashboard",
      revenue: "Total Revenue",
      orders: "Total Orders",
      products: "Total Products",
      pending: "Pending Orders",
      recent_orders: "Recent Orders",
      no_orders: "No orders yet",
      currency: "DZD",
    },
    products: {
      title: "Products",
      add: "Add product",
      search: "Search products…",
      name: "Product name",
      desc: "Description",
      price: "Price (DZD)",
      stock: "Stock quantity",
      category: "Category",
      image: "Product image",
      image_hint: "JPG, PNG or WebP. Max 2MB.",
      no_image: "No image",
      active: "Active",
      inactive: "Inactive",
      in_stock: "In stock",
      out_of_stock: "Out of stock",
      edit: "Edit",
      delete: "Delete",
      save: "Save changes",
      adding: "Adding…",
      saving: "Saving…",
      delete_confirm:
        "Are you sure you want to delete this product? This cannot be undone.",
      no_products: "No products yet",
      add_first: "Add your first product to get started.",
      edit_title: "Edit product",
      add_title: "Add new product",
      cancel: "Cancel",
    },
    orders: {
      title: "Orders",
      all: "All",
      pending: "Pending",
      confirmed: "Confirmed",
      shipped: "Shipped",
      delivered: "Delivered",
      cancelled: "Cancelled",
      order_id: "Order ID",
      customer: "Customer",
      phone: "Phone",
      address: "Address",
      items: "Items",
      total: "Total",
      status: "Status",
      date: "Date",
      update: "Update status",
      updating: "Updating…",
      details: "Order details",
      no_orders: "No orders in this category",
      product: "Product",
      qty: "Qty",
      price: "Price",
    },
    store: {
      title: "Store Settings",
      identity_tab: "Identity",
      colors_tab: "Colors",
      banner_tab: "Banner",
      store_name: "Store name",
      description: "Description",
      slug: "Store URL slug",
      slug_hint: "Your store will be at: /store/",
      primary_color: "Primary color",
      card_bg: "Card background",
      page_bg: "Page background",
      corner_radius: "Corner radius (px)",
      banner_image: "Banner image",
      banner_title: "Banner title",
      banner_subtitle: "Banner subtitle",
      save: "Save changes",
      saving: "Saving…",
      saved: "Changes saved!",
      preview: "Live preview",
      create_first: "Create your store first",
      create_btn: "Create store",
      creating: "Creating…",
      logo: "Store logo",
    },
    public: {
      order_btn: "Order now",
      order_title: "Place your order",
      customer_name: "Your name",
      phone: "Phone number",
      address: "Delivery address",
      qty: "Quantity",
      total: "Total",
      submit: "Place order",
      submitting: "Submitting…",
      success_title: "Order placed!",
      success_msg:
        "Your order has been received. The merchant will contact you soon.",
      back: "Continue shopping",
      empty: "No products available yet.",
      loading: "Loading store…",
      not_found: "Store not found",
      out_of_stock: "Out of stock",
      sar: "DZD",
    },
    common: {
      cancel: "Cancel",
      confirm: "Confirm",
      close: "Close",
      loading: "Loading…",
      error: "Something went wrong",
      retry: "Try again",
    },
  },

  ar: {
    nav: {
      dashboard: "لوحة التحكم",
      products: "المنتجات",
      orders: "الطلبات",
      store: "إعدادات المتجر",
      publicStore: "متجري",
      logout: "تسجيل الخروج",
    },
    landing: {
      hero_eyebrow: "مرحبًا بك في فيندورز",
      hero_title: "متجرك،\nفي كل مكان.",
      hero_subtitle:
        "أطلق متجرك الإلكتروني في دقائق. أدِر منتجاتك، تابع طلباتك، وخصّص علامتك التجارية — كل شيء في مكان واحد.",
      cta_start: "ابدأ مجانًا",
      cta_login: "تسجيل الدخول",
      tab_setup: "إنشاء المتجر",
      tab_products: "المنتجات",
      tab_orders: "الطلبات",
      tab_customize: "التخصيص",
      feature_title: "كل ما تحتاجه\nللبيع أونلاين.",
      f1_title: "متجر فوري",
      f1_desc: "احصل على متجر جميل ومميز في ثوانٍ. شارك رابطك وابدأ البيع.",
      f2_title: "إدارة المنتجات",
      f2_desc: "أضف وعدّل ونظّم منتجاتك. ارفع الصور وحدد مستويات المخزون.",
      f3_title: "تتبع الطلبات",
      f3_desc:
        "شاهد كل طلب في الوقت الفعلي. حدّث الحالات وأبقِ عملاءك على اطلاع.",
      f4_title: "علامة مخصصة",
      f4_desc: "اختر ألوانك، ارفع صورة البنر، واجعل المتجر بصمتك.",
      trusted: "موثوق به من قِبل الأعمال النامية",
      cta_section: "مستعد لبدء البيع؟",
      cta_sub: "أنشئ متجرك المجاني اليوم. لا يلزم بطاقة ائتمانية.",
      cta_btn: "أنشئ متجرك",
    },
    auth: {
      login_title: "مرحبًا بعودتك",
      login_sub: "سجّل دخولك إلى حساب فيندورز",
      register_title: "أنشئ متجرك",
      register_sub: "ابدأ البيع في دقائق — مجانًا",
      name: "الاسم الكامل",
      email: "البريد الإلكتروني",
      password: "كلمة المرور",
      login_btn: "تسجيل الدخول",
      register_btn: "إنشاء حساب",
      no_account: "ليس لديك حساب؟",
      have_account: "لديك حساب بالفعل؟",
      register_link: "أنشئ واحدًا",
      login_link: "سجّل دخولك",
      logging_in: "جاري الدخول…",
      registering: "جاري إنشاء الحساب…",
    },
    dashboard: {
      title: "لوحة التحكم",
      revenue: "إجمالي الإيرادات",
      orders: "إجمالي الطلبات",
      products: "إجمالي المنتجات",
      pending: "الطلبات المعلقة",
      recent_orders: "أحدث الطلبات",
      no_orders: "لا توجد طلبات بعد",
      currency: "دج",
    },
    products: {
      title: "المنتجات",
      add: "إضافة منتج",
      search: "ابحث عن منتج…",
      name: "اسم المنتج",
      desc: "الوصف",
      price: "السعر (دج)",
      stock: "الكمية في المخزون",
      category: "الفئة",
      image: "صورة المنتج",
      image_hint: "JPG أو PNG أو WebP. الحد الأقصى 2MB.",
      no_image: "لا توجد صورة",
      active: "نشط",
      inactive: "غير نشط",
      in_stock: "متوفر",
      out_of_stock: "نفد من المخزون",
      edit: "تعديل",
      delete: "حذف",
      save: "حفظ التغييرات",
      adding: "جاري الإضافة…",
      saving: "جاري الحفظ…",
      delete_confirm: "هل أنت متأكد من حذف هذا المنتج؟ لا يمكن التراجع.",
      no_products: "لا توجد منتجات بعد",
      add_first: "أضف منتجك الأول للبدء.",
      edit_title: "تعديل المنتج",
      add_title: "إضافة منتج جديد",
      cancel: "إلغاء",
    },
    orders: {
      title: "الطلبات",
      all: "الكل",
      pending: "قيد الانتظار",
      confirmed: "مؤكد",
      shipped: "تم الشحن",
      delivered: "تم التسليم",
      cancelled: "ملغي",
      order_id: "رقم الطلب",
      customer: "العميل",
      phone: "الهاتف",
      address: "العنوان",
      items: "المنتجات",
      total: "الإجمالي",
      status: "الحالة",
      date: "التاريخ",
      update: "تحديث الحالة",
      updating: "جاري التحديث…",
      details: "تفاصيل الطلب",
      no_orders: "لا توجد طلبات في هذه الفئة",
      product: "المنتج",
      qty: "الكمية",
      price: "السعر",
    },
    store: {
      title: "إعدادات المتجر",
      identity_tab: "الهوية",
      colors_tab: "الألوان",
      banner_tab: "البنر",
      store_name: "اسم المتجر",
      description: "الوصف",
      slug: "رابط المتجر",
      slug_hint: "سيكون متجرك على: /store/",
      primary_color: "اللون الرئيسي",
      card_bg: "خلفية البطاقات",
      page_bg: "خلفية الصفحة",
      corner_radius: "تدوير الزوايا (px)",
      banner_image: "صورة البنر",
      banner_title: "عنوان البنر",
      banner_subtitle: "وصف البنر",
      save: "حفظ التغييرات",
      saving: "جاري الحفظ…",
      saved: "تم الحفظ!",
      preview: "معاينة مباشرة",
      create_first: "أنشئ متجرك أولًا",
      create_btn: "إنشاء المتجر",
      creating: "جاري الإنشاء…",
      logo: "شعار المتجر",
    },
    public: {
      order_btn: "اطلب الآن",
      order_title: "أتمم طلبك",
      customer_name: "اسمك",
      phone: "رقم الهاتف",
      address: "عنوان التوصيل",
      qty: "الكمية",
      total: "الإجمالي",
      submit: "تأكيد الطلب",
      submitting: "جاري الإرسال…",
      success_title: "تم استلام طلبك!",
      success_msg: "تم استلام طلبك بنجاح. سيتواصل معك البائع قريبًا.",
      back: "متابعة التسوق",
      empty: "لا توجد منتجات متاحة بعد.",
      loading: "جاري تحميل المتجر…",
      not_found: "المتجر غير موجود",
      out_of_stock: "نفد من المخزون",
      sar: "دج",
    },
    common: {
      cancel: "إلغاء",
      confirm: "تأكيد",
      close: "إغلاق",
      loading: "جاري التحميل…",
      error: "حدث خطأ ما",
      retry: "حاول مجددًا",
    },
  },
};

/* ─── Context ───────────────────────────────── */
const LangContext = createContext(null);

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem("lang") || "ar");

  const dir = lang === "ar" ? "rtl" : "ltr";

  useEffect(() => {
    document.documentElement.lang = lang;
    document.documentElement.dir = dir;
    localStorage.setItem("lang", lang);
  }, [lang, dir]);

  const toggleLang = useCallback(() => {
    setLang((prev) => (prev === "ar" ? "en" : "ar"));
  }, []);

  const t = useCallback(
    (section, key) => {
      return translations[lang]?.[section]?.[key] ?? key;
    },
    [lang],
  );

  return (
    <LangContext.Provider value={{ lang, dir, toggleLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error("useLang must be used within LangProvider");
  return ctx;
}
